catalog: workspace
schema: default
landing_path: /Volumes/workspace/default/medallion_demo_landing
bronze_path: dbfs:/FileStore/medallion_demo/bronze
silver_path: dbfs:/FileStore/medallion_demo/silver
gold_path: dbfs:/FileStore/medallion_demo/gold